# Generated by Django 3.2.8 on 2021-11-24 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20211117_2006'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='no_photo.jpg', upload_to='gallery_images')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='gallery',
            field=models.ManyToManyField(to='blog.GalleryImage'),
        ),
    ]
