# Generated by Django 3.2.9 on 2021-11-25 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20211124_2140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='gallery',
        ),
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(default='no_photo.jpg', upload_to='gallery_images'),
        ),
    ]
