# Generated by Django 3.2.9 on 2021-12-14 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_postfavorite_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='country_code',
            field=models.CharField(default='BE', max_length=2),
        ),
        migrations.AddField(
            model_name='post',
            name='region_city',
            field=models.CharField(default='1000 City of Brussels, Brussels-Capital', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='road_num',
            field=models.CharField(default='Grand Place 14', max_length=100),
        ),
    ]
