# Generated by Django 3.2.8 on 2021-12-20 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20211219_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='nb_etage',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='post',
            name='situe_etage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='type_bien',
            field=models.CharField(default='Maison', max_length=20),
        ),
    ]
