# Generated by Django 3.2.8 on 2021-12-20 22:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_qna'),
    ]

    operations = [
        migrations.AddField(
            model_name='qna',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
