# Generated by Django 3.2.8 on 2021-12-24 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_reponse'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GalleryImage',
        ),
    ]
