# Generated by Django 3.2.8 on 2021-12-18 14:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='date_recieved',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
