# Generated by Django 3.2.8 on 2021-12-19 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_notification_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='criteria',
            name='sell_method',
            field=models.BooleanField(default=True),
        ),
    ]
